export class MOCKS_PRODUCTOS {
    static stocks = `[
        {
        "foto":"assets/imgs/beefeater",
        "nombre":""
        "precio":,
        "precio_unidad":,
        "oferta":,
        "precio_oferta":},
        {
        "foto":"",
        "nombre":"",
        "precio":,
        "precio_unidad":,
        "oferta":,
        "precio_oferta":},
           {
        "foto":"",
        "nombre":"",
        "precio":,
        "precio_unidad":,
        "oferta":,
        "precio_oferta":}
        {
        "foto":"",
        "nombre":"",
        "precio":,
        "precio_unidad":,
        "oferta":,
        "precio_oferta":}
        {
        "foto":"",
        "nombre":"",
        "precio":,
        "precio_unidad":,
        "oferta":,
        "precio_oferta":}
        {
        "foto":"",
        "nombre":"",
        "precio":,
        "precio_unidad":,
        "oferta":,
        "precio_oferta":}
        {
        "foto":"",
        "nombre":"",
        "precio":,
        "precio_unidad":,
        "oferta":,
        "precio_oferta":}
        {
        "foto":"",
        "nombre":"",
        "precio":,
        "precio_unidad":,
        "oferta":,
        "precio_oferta":}
        {
        "foto":"",
        "nombre":"",
        "precio":,
        "precio_unidad":,
        "oferta":,
        "precio_oferta":}
        {
        "foto":"",
        "nombre":"",
        "precio":,
        "precio_unidad":,
        "oferta":,
        "precio_oferta":}
    ]`;
}
